name: Release

on:
  push:
    tags:
      - boost-*

jobs:
  make-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.ref_name }}
          submodules: true

      - name: Cleanup
        shell: bash
        run: |
          # Remove all .git folders & files as well as .github folders and .git, .gitattribute etc. files
          find ${{ github.ref_name }} -name ".git*" -prune -exec rm -rf {} +
          # Remove CI configs
          find ${{ github.ref_name }} -type f \( \
            -name "appveyor.yml" -o \
            -name ".appveyor.yml" -o \
            -name "azure-pipelines.yml" -o \
            -name ".azure-pipelines.yml" -o \
            -name "circle.yml" -o \
            -name ".cirrus.yml" -o \
            -name "codecov.yml" -o \
            -name ".codecov.yml" -o \
            -name ".coveralls.yml" -o \
            -name ".drone.star" -o \
            -name ".travis.yml" -o \
            -false \) -delete
            
      - name: Create Linux Archives
        if: runner.os == 'Linux'
        run: |
          tar -czf ${{ github.ref_name }}.tar.gz ${{ github.ref_name }}
          tar -cJf ${{ github.ref_name }}.tar.xz ${{ github.ref_name }}
      - name: Create Windows archives
        if: runner.os == 'Windows'
        run: |
          7z ${{ github.ref_name }}.zip ${{ github.ref_name }}
          7z ${{ github.ref_name }}.7z ${{ github.ref_name }}

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.ref_name }}.*
